# frozen_string_literal: true

AllCops:
  TargetRubyVersion: 3.2.0
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'tmp/**/*'
plugins:
  - rubocop-rails
Style/StringLiterals:
  EnforcedStyle: single_quotes
Style/WordArray:
  EnforcedStyle: percent
Style/SymbolArray:
  EnforcedStyle: percent
Style/Documentation:
  Enabled: false
Layout/LineLength:
  Max: 150
Metrics/MethodLength:
  Max: 20
Metrics/ClassLength:
  Max: 150
Metrics/ModuleLength:
  Max: 150
Metrics/BlockLength:
  Max: 30
  Exclude:
    - 'spec/**/*'
Style/FrozenStringLiteralComment:
  Enabled: true
Rails/UniqueValidationWithoutIndex:
  Enabled: true