services:
  app:
    build:
      context: .
      dockerfile: docker/development/Dockerfile
    volumes:
      - .:/app
    ports:
      - 3000:3000
    environment:
      - RAILS_ENV=development
    command: ["/docker/entrypoint.sh"]

