
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  url: <%= Rails.application.credentials.dig(:database_url) %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default